version: '3.5'
services:
  react:
    build:
      context: ./react
    volumes:
      - ./react:/usr/react
    image: react_app
    container_name: react
    ports: 
      - 3005:3000

  eukles_api:
    build:
      context: ./eukles_api
    image: eukles_api
    container_name: eukles
    env_file:
      - ./eukles_api/.env
    volumes:
      - ./eukles_api:/var/www/html
    depends_on:
      - db
    command: bash -c "composer install --no-interaction --no-scripts --prefer-dist && php bin/console doctrine:database:create && php bin/console doctrine:migrations:generate &&  php bin/console doctrine:migrations:diff && php bin/console doctrine:migrations:migrate --force && php-fpm"

  reverse_proxy:
    build:
      context: ./eukles_api/reverse_proxy
    image: reverse_proxy
    container_name: reverse_proxy
    depends_on:
      - eukles_api
    ports:
      - 8002:80
    volumes:
      - ./eukles_api:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      DB_PASSWORD: root
    container_name: db
    volumes:
      - ./var/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    container_name: phpmyadmin
    environment:
      - PMA_PORT=3307
